# Generated by Django 3.2.25 on 2024-05-23 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
